spring.application.name = chatapp

# DATABASE
spring.datasource.driver-class-name = com.mysql.jdbc.Driver

spring.datasource.url=jdbc:mysql://gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/test
spring.datasource.username=2yby4nf6gstCEPZ.root
spring.datasource.password=jrzuegVA043yv4pa


# JPA / HIBERNATE
spring.jpa.show-sql = true
spring.jpa.hibernate.ddl-auto = none
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect

# Mở công cụ hiển thị metrics (đo lường) ra ngoài web
management.endpoints.web.exposure.include=metrics

# (Tùy chọn) Định dạng JSON đẹp mắt hơn để dễ đọc
management.info.env.enabled=true