spring.application.name = chatapp

# DATABASE
spring.datasource.driver-class-name = com.mysql.jdbc.Driver

spring.datasource.url=jdbc:mysql://3KgJ2sdkbpuQpPN.root:QTw3itYCwlKy8k0G@gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/test?sslMode=VERIFY_IDENTITY
spring.datasource.username=3KgJ2sdkbpuQpPN.root
spring.datasource.password=QTw3itYCwlKy8k0G



# JPA / HIBERNATE
spring.jpa.show-sql = true
spring.jpa.hibernate.ddl-auto = none
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect