spring.application.name = chatapp

# DATABASE
spring.datasource.driver-class-name = com.mysql.jdbc.Driver

spring.datasource.url = jdbc:mysql://127.0.0.1:3306/chatappdb
spring.datasource.username = root
spring.datasource.password = dragonJJk@412
 

# JPA / HIBERNATE
spring.jpa.show-sql = true
spring.jpa.hibernate.ddl-auto = none
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect

# Session
server.servlet.session.timeout = 30m
server.servlet.session.store-type = jpa

# upload size
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=50MB

server.address=0.0.0.0